from __future__ import annotations

from typing import Any, Protocol


class WarehouseProvider(Protocol):
    def capabilities(self) -> dict[str, Any]: ...

    def health_check(self) -> dict[str, Any]: ...

    def describe_relation(self, relation: str) -> dict[str, Any]: ...

    def dry_run(self, sql: str) -> dict[str, Any]: ...

    def execute_read(self, sql: str) -> dict[str, Any]: ...

    def cancel(self, job_id: str) -> dict[str, Any]: ...
